### ISSUE TITLE
Rename / Collaborate

### ISSUE THREAD

**Issue by mehcode** [filipegoncalves/rust-config#22]
@filipegoncalves and contributors,

I'm working on a modern configuration library for Rust (in the spirit of [node-config](https://github.com/lorenwest/node-config), [viper](https://github.com/spf13/viper), [flask](https://github.com/mbr/flask-appconfig), etc.).

 - Layered — Configuration can come from several areas, each with its own priority
 - 12-factor — Strong support for binding environment variables
 - Loosely-typed — A configuration value stored as `1` can be retrieved with `config::get_bool` as `true`

I'd like to use the name `config` in crates.io for my package, [config-rs](https://github.com/mehcode/config-rs). This project could be more aptly called "libconfig" on crates.io as it is a libconfig file format parser.

---

This project can also become simpler / reduce its scope and expose an API for `config-rs`. From the usage side it would look like this.

```rust
// Merge conf file into configuration
config::merge(config::File::with_name("tests/sample.conf")).unwrap();

// Access
assert_eq!(config::get_str("application.window.title"), Some("My Application"));
assert_eq!(config::get_int("application.window.size.w"), Some(640));
```

---

Thoughts? I can do any heavy lifting in this project if needed.

**Comment by filipegoncalves** [comment]
[We're coordinating over e-mail, but I'll post here a quick summary nevertheless]

Sorry, I don't have the time to work on this at the moment. I'm happy to merge your PRs though, so feel free to send patches. I'm not sure how to rename this in crates, but it seems we're not the first to have this problem: https://github.com/rust-lang/crates.io/issues/166

Let's move the renaming discussion to the email thread. Thanks for working on this!

I'm closing this for now.
